### ISSUE TITLE
Club Logo Not displaying Correctly

### ISSUE THREAD

**Issue by anujgrp** [cpotey/fpl-stats#1]
Club Logo are not displaying correctly or even close. 
![image](https://user-images.githubusercontent.com/43801412/52893664-25ea6900-31e2-11e9-8ef5-f91a1e39d84b.png)

**Comment by anujgrp** [comment]
Solved it by commenting 
   /* background-image: url('../assets/badges-100.png');*/  on Line 866 Badge.css

**Comment by anujgrp** [comment]
Same for Player Search Page. But cudnt fig out th eprob this time
![image](https://user-images.githubusercontent.com/43801412/52893730-128bcd80-31e3-11e9-9e95-86442d5ce193.png)

**Comment by cpotey** [comment]
Thanks for letting me know, I think I had a cached version which was working so couldn't see the issues.
I've fixed the search page icons too.

Cheers :)
